---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
resources:
  - ../base
patches:
- path: deployment_patch.yaml
  target:
    version: v1
    kind: Deployment
    name: dev-finder-deploy 

images:
  - name: devfinder
    newName: 459137896070.dkr.ecr.us-east-1.amazonaws.com/devfinder # {"$imagepolicy": "sock-shop:sock-shop-front-end:name"}
    newTag: latest # {"$imagepolicy": "sock-shop:sock-shop-front-end:tag"}
