apiVersion: v1
kind: Service
metadata:
  name: dev-finder-svc
  labels:
    app.kubernetes.io/name: dev-finder
    app.kubernetes.io/instance: dev-finder
    app.kubernetes.io/component: service
    app.kubernetes.io/created-by: eks-workshop
spec:
  selector:
    app.kubernetes.io/name: dev-finder
    app.kubernetes.io/instance: dev-finder
    app.kubernetes.io/component: service
  ports:
  - port: 80
    targetPort: 80
  type: NodePort