apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-finder-deploy
  labels:
    app.kubernetes.io/created-by: eks-workshop
    app.kubernetes.io/type: app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dev-finder
      app.kubernetes.io/instance: dev-finder
      app.kubernetes.io/component: service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dev-finder
        app.kubernetes.io/instance: dev-finder
        app.kubernetes.io/component: service
        app.kubernetes.io/created-by: eks-workshop
    spec:
      containers:
      - name: dev-finder
        image: roxsross12/dev-finder:1.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80