version: 0.2

phases:
  pre_build:
    commands:
      - echo Starting install `date`
      - curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest

  build:
    commands:
      - echo Build started on `date`
      - echo Scanning with horusec...
      - horusec start -p="./" -e="true" -o=json -O=$(pwd)/report_horusec.json || EXIT_CODE=$?

  post_build:
    commands:
      - echo Build completed on `date`
      - cat report_horusec.json
artifacts:
  files: report_horusec.json